import{loadCountry,loadAll}from'../store';
import{calculateFees,generateProviderPayouts,DEFAULT_PLATFORM_CONFIG}from'../silverconnect';
import{createLedger,bankTxToJournal,generateBas,generateAuReturn,generateCaReturn}from'../ledger';
import{categorise,AU_R,CA_R}from'../bankFeed';
import{generateQuarterlyBas}from'../basAu';
import{generateFinancialStatements}from'../financialStatements';
const P=[[/balance|bank|account|how much.*have/i,'bank'],[/bas|gst.*return|gst.*owe|activity statement/i,'bas'],[/annual.*return|tax.*return|company tax|t2|lodge|how much tax/i,'annual'],[/pay.*to|send.*money|transfer|initiate.*payment|interac|payto/i,'pay'],[/p.l|profit|loss|revenue|income|financial|am i profitable/i,'pnl'],[/platform.*fee|sc.*fee|commission|split|booking/i,'sc'],[/payout|provider.*pay/i,'payouts'],[/categoris|classify|sort.*trans/i,'cat'],[/forecast|predict|cash.*flow|runway|burn/i,'forecast'],[/reconcil|match|duplicate/i,'recon'],[/cost|saving|compare.*stripe|vs.*stripe|vs.*xero/i,'cost'],[/hi|hello|hey|g.day/i,'greet'],[/help|what can you|commands/i,'help']];
export function classify(msg){const m=msg.toLowerCase();let p={};if(/au|anz|australia/i.test(m))p.country='AU';if(/ca|rbc|canada/i.test(m))p.country='CA';const a=m.match(/\$(\d+)/);if(a)p.amount=+a[1];for(const[pat,t]of P){if(pat.test(m))return{tool:t,params:p};}return{tool:'help',params:p};}
function r(n){return Math.round(n*100)/100;}
function bank(p){const t=p.country?loadCountry(p.country):loadAll();const i=t.filter(x=>x.amount>0).reduce((s,x)=>s+x.amount,0);const e=t.filter(x=>x.amount<0).reduce((s,x)=>s+Math.abs(x.amount),0);return{ok:true,data:{balance:r(i-e),income:r(i),expenses:r(e),count:t.length},msg:'Balance: $'+r(i-e)+' | Income: $'+r(i)+' | Expenses: $'+r(e)+' ('+t.length+' txs)'};}
function bas(p){const t=loadCountry('AU');if(!t.length)return{ok:false,data:{},msg:'No AU data. Upload ANZ CSV.'};const fy=new Date().getMonth()>=6?new Date().getFullYear():new Date().getFullYear()-1;const q=generateQuarterlyBas(t,fy);const l=q[q.length-1];return{ok:true,data:{quarters:q},msg:l?'BAS Q'+l.quarter+': GST $'+l.gst_on_sales_1a?.toFixed(2)+' | ITCs $'+l.gst_on_purchases_1b?.toFixed(2)+' | Net $'+l.net_gst_payable?.toFixed(2):'No data'};}
function annual(p){const c=p.country||'AU',t=loadCountry(c);if(!t.length)return{ok:false,data:{},msg:'No '+c+' data.'};const l=createLedger('PHL',c);const rules=c==='AU'?AU_R:CA_R;for(const tx of t){const{a,t:tc}=categorise(tx.description,tx.amount,rules);l.entries.push(bankTxToJournal(tx,a,tc,c));}const ret=c==='AU'?generateAuReturn(l,new Date().getFullYear()-1):generateCaReturn(l,new Date().getFullYear());return{ok:true,data:ret,msg:JSON.stringify(ret)};}
function pay(p){const cur=p.country==='CA'?'CAD':'AUD',rail=cur==='AUD'?'PayTo ($0)':'Interac ($0.25)';if(!p.amount)return{ok:true,data:{},msg:'Say "pay $500 to provider". Rail: '+rail};return{ok:true,data:{amount:p.amount,rail},msg:'Ready: $'+p.amount+' '+cur+' via '+rail};}
function pnl(p){const t=p.country?loadCountry(p.country):loadAll();if(!t.length)return{ok:false,data:{},msg:'No data.'};const fs=generateFinancialStatements(new Date().toISOString().slice(0,10),t);const pl=fs.profit_loss||{};return{ok:true,data:fs,msg:'Revenue $'+(pl.revenue||0).toFixed(0)+' | Expenses $'+(pl.expenses||0).toFixed(0)+' | Net $'+(pl.net_income||0).toFixed(0)};}
function sc(p){if(p.amount){const f=calculateFees(p.amount,DEFAULT_PLATFORM_CONFIG);return{ok:true,data:f,msg:'$'+p.amount+': Platform $'+f.platform_fee+' | Provider $'+f.provider_payout};}return{ok:true,data:DEFAULT_PLATFORM_CONFIG,msg:'15% platform fee | 85% provider | 10% GST'};}
function payouts(){const t=loadCountry('AU').filter(x=>x.amount>0).slice(0,12);if(!t.length)return{ok:false,data:{},msg:'No bookings.'};const bk=t.map((x,i)=>({booking_id:'BK-'+i,gross_amount:x.amount,provider_id:'P'+(i%4),provider_name:'Provider '+(i%4+1),status:'completed'}));const py=generateProviderPayouts(bk);return{ok:true,data:{payouts:py},msg:py.length+' providers | $'+py.reduce((s,x)=>s+x.net_payout,0).toFixed(0)};}
function cat(p){const c=p.country||'AU',t=loadCountry(c),rules=c==='AU'?AU_R:CA_R;if(!t.length)return{ok:false,data:{},msg:'No data.'};const d={};for(const tx of t){const{a}=categorise(tx.description,tx.amount,rules);d[a]=(d[a]||0)+1;}return{ok:true,data:d,msg:t.length+' txs in '+Object.keys(d).length+' accounts'};}
function forecast(){const t=loadAll();if(!t.length)return{ok:false,data:{},msg:'No data.'};const mo=Math.max(1,new Set(t.map(x=>x.date.slice(0,7))).size);const ai=r(t.filter(x=>x.amount>0).reduce((s,x)=>s+x.amount,0)/mo);const ae=r(t.filter(x=>x.amount<0).reduce((s,x)=>s+Math.abs(x.amount),0)/mo);return{ok:true,data:{avgInc:ai,avgExp:ae,net:r(ai-ae)},msg:'$'+ai+'/mo in | $'+ae+'/mo out | Net $'+r(ai-ae)+'/mo'};}
function recon(p){const t=loadCountry(p.country||'AU');const seen=new Map();let d=0;for(const x of t){const k=x.date+'|'+x.amount;if(seen.has(k))d++;else seen.set(k,x);}return{ok:true,data:{total:t.length,dupes:d},msg:t.length+' checked | '+d+' duplicates'};}
function cost(){const v=50000,n=250,sA=r(v*0.017+n*0.3),sC=r(v*0.029+n*0.3);return{ok:true,data:{stripe_au:sA,stripe_ca:sC,phledger:0},msg:'Save: AU $'+sA+'/mo + CA $'+r(sC-n*0.25)+'/mo + Xero $65/mo = ~$'+r((sA+sC+65)*12)+'/yr'};}
function greet(){return{ok:true,data:{},msg:"G'day! PHLedger Agent — 100% free.\nTry: balance, BAS, tax return, pay $X, P&L, forecast, cost savings"};}
function help(){return{ok:true,data:{},msg:"Commands: balance, BAS, tax return, pay $X, P&L, platform fees, payouts, categorise, forecast, reconcile, cost vs stripe.\nAll free."};}
export async function processMessage(msg){const{tool,params}=classify(msg);let res;switch(tool){case'bank':res=bank(params);break;case'bas':res=bas(params);break;case'annual':res=annual(params);break;case'pay':res=pay(params);break;case'pnl':res=pnl(params);break;case'sc':res=sc(params);break;case'payouts':res=payouts();break;case'cat':res=cat(params);break;case'forecast':res=forecast();break;case'recon':res=recon(params);break;case'cost':res=cost();break;case'greet':res=greet();break;default:res=help();}return{role:'agent',content:res.msg,data:res.data,timestamp:new Date().toISOString()};}
